export {default as Navbar} from './Navbar'
export {default as App} from './App'
export {default as Activities} from './Activities'
export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as MyRoutines} from './MyRoutines'
export {default as Register} from './Register'
export {default as Routines} from './Routines'